
openapi: 3.1.0
info:
  title: Touch by Gennaro Deploy API
  version: 1.0.0
servers:
  - url: http://192.168.178.31:5055
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /deploy:
    post:
      summary: Run the idempotent WordPress deploy
      responses:
        '200':
          description: Deploy finished
        '401':
          description: Unauthorized
