
name: Deploy Touch by Gennaro

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, wp-lxc]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Ensure zip tool
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip

      - name: Sanitize HTML (strip comments + Framer/HTTrack)
        run: |
          shopt -s globstar nullglob
          for f in site/**/*.html site/*.html; do
            # verwijder HTML comments met Framer/HTTrack tekst
            sed -i -E '/Built with Framer|Mirrored from|Made in Framer|More Templates|Use for Free/d' "$f"
            # verwijder losse "Made in Framer" anchors
            sed -i -E 's@<a[^>]*>Made in Framer</a>@@Ig' "$f" || true
          done

      - name: Prepare /home/wpbot and build site.zip
        run: |
          mkdir -p /home/wpbot
          if [ -d "./site" ]; then
            cd site && zip -r /home/wpbot/site.zip . && cd -
          else
            echo "❌ Map ./site bestaat niet. Zet je HTML-site in ./site/ en push opnieuw."
            exit 1
          fi
          ls -lh /home/wpbot/site.zip

      - name: Run idempotent deploy (WP-CLI)
        run: |
          sudo bash ./examples/deploy.sh
